name: SonarCloud Analysis & Auto Issue Creation

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (Fix shallow clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install  

      - name: Get Latest Git Tag
        run: |
          TAG=$(git describe --tags --always || echo "0.0.1")
          echo "SONAR_VERSION=$TAG" >> $GITHUB_ENV
          echo "Using SonarCloud version: $TAG"

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonarqube-scanner \
            -Dsonar.organization=front-end-project \
            -Dsonar.projectKey=manoj-wws_Sonar-Qube-Tester \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.projectVersion=${{ env.SONAR_VERSION }}

      - name: Fetch SonarCloud Issues
        id: sonar_issues
        run: |
          SONAR_URL="https://sonarcloud.io/api/issues/search?organization=front-end-project&componentKeys=manoj-wws_Sonar-Qube-Tester&resolved=false"
          RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "$SONAR_URL")

          # Debugging: Print the full response
          echo "SonarCloud API Response:"
          echo "$RESPONSE"

          # Extract issue count
          ISSUE_COUNT=$(echo "$RESPONSE" | jq '.total')
          echo "Total Issues Found: $ISSUE_COUNT"
          echo "issue_count=$ISSUE_COUNT" >> $GITHUB_ENV

          if [[ "$ISSUE_COUNT" -gt 0 ]]; then
            ISSUE_MESSAGE=$(echo "$RESPONSE" | jq -r '.issues[0].message')
            ISSUE_FILE=$(echo "$RESPONSE" | jq -r '.issues[0].component')
            ISSUE_LINE=$(echo "$RESPONSE" | jq -r '.issues[0].line')
            ISSUE_SEVERITY=$(echo "$RESPONSE" | jq -r '.issues[0].severity')
            ISSUE_RULE_URL="https://sonarcloud.io/organizations/front-end-project/issues?open=$(echo "$RESPONSE" | jq -r '.issues[0].key')"

            echo "First Issue: $ISSUE_MESSAGE in $ISSUE_FILE (Line: $ISSUE_LINE, Severity: $ISSUE_SEVERITY)"

            # Save values to ENV file
            echo "issue_message=$ISSUE_MESSAGE" >> $GITHUB_ENV
            echo "issue_file=$ISSUE_FILE" >> $GITHUB_ENV
            echo "issue_line=$ISSUE_LINE" >> $GITHUB_ENV
            echo "issue_severity=$ISSUE_SEVERITY" >> $GITHUB_ENV
            echo "issue_rule_url=$ISSUE_RULE_URL" >> $GITHUB_ENV
          else
            echo "No issues found by SonarCloud."
          fi

      - name: Ensure "SonarCloud" Label Exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! gh label list --repo ${{ github.repository }} | grep -q "SonarCloud"; then
            echo "Creating 'SonarCloud' label..."
            gh label create "SonarCloud" --description "Issues found by SonarCloud analysis" --color "#0e8a16" --repo ${{ github.repository }}
          else
            echo "'SonarCloud' label already exists."
          fi

      - name: Create GitHub Issue (if new issues found)
        if: env.issue_count > 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking for extracted issue data..."
          echo "Message: $ISSUE_MESSAGE"
          echo "File: $ISSUE_FILE"
          echo "Severity: $ISSUE_SEVERITY"
          echo "Rule URL: $ISSUE_RULE_URL"

          if [[ -z "$ISSUE_MESSAGE" || -z "$ISSUE_FILE" || -z "$ISSUE_SEVERITY" || -z "$ISSUE_RULE_URL" ]]; then
            echo "⚠️ No valid issue data received from SonarCloud. Skipping issue creation."
            exit 0
          fi

          ISSUE_TITLE="🚨 [$ISSUE_SEVERITY] SonarCloud Issue in $(basename $ISSUE_FILE)"
          ISSUE_BODY="**Issue:** $ISSUE_MESSAGE\n\n
          **File:** \`$(basename $ISSUE_FILE)\`\n
          **Line:** $ISSUE_LINE\n
          **Severity:** $ISSUE_SEVERITY\n
          **SonarCloud Report:** [View Issue]($ISSUE_RULE_URL)\n\n
          Please check and resolve this issue."

          gh issue create --title "$ISSUE_TITLE" --body "$ISSUE_BODY" --label "SonarCloud" --repo ${{ github.repository }}
